accounts:
  - name: rickmak
    coins: ["20000token", "100000000stake"]
  - name: hochiw
    coins: ["20000token", "100000000stake"]
  - name: cheungpat
    coins: ["20000token", "100000000stake"]
  - name: chihimng
    coins: ["20000token", "100000000stake"]
  - name: limouren
    coins: ["20000token", "100000000stake"]
  - name: overflow
    coins: ["200000token", "100000000stake"]
validator:
  name: rickmak
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: overflow
  coins: ["5token", "100000stake"]
